=== IstvnRozsa/xml_project/data/schema09.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="teams">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="team" type="teamType" maxOccurs="3" minOccurs="1">
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="teamType">
        <xs:sequence>
            <xs:element name="teamName" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="teamLosses" type="xs:integer" maxOccurs="1" minOccurs="1"/>
            
        </xs:sequence>
        <xs:attribute name="id" type="xs:integer" use="required"/>
    </xs:complexType>
</xs:schema>

=== IstvnRozsa/xml_project/outputs/09xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<teams xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="schema09.xsd">
    <team id="9">
        <teamName>Ottawa Senators</teamName>
        <teamLosses>47</teamLosses>
    </team>
    <team id="26">
        <teamName>Los Angeles Kings</teamName>
        <teamLosses>42</teamLosses>
    </team>
    <team id="1">
        <teamName>New Jersey Devils</teamName>
        <teamLosses>41</teamLosses>
    </team>
</teams>
