=== IstvnRozsa/xml_project/data/schema08.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="teams">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="team" type="teamType" maxOccurs="unbounded" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    <xs:complexType name="teamType">
        <xs:sequence>
            <xs:element name="teamName" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="teamStats" type="teamStatsType" maxOccurs="1" minOccurs="1"/>
            <xs:element name="players" type="playersType" maxOccurs="1" minOccurs="1"/>
            
        </xs:sequence>
        <xs:attribute name="id" type="xs:integer" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="teamStatsType">
        <xs:sequence>
            <xs:element name="wins" type="xs:integer" maxOccurs="1" minOccurs="1"/>
            <xs:element name="losses" type="xs:integer" maxOccurs="1" minOccurs="1"/>
            <xs:element name="pts" type="xs:integer" maxOccurs="1" minOccurs="1"/>
            
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="playersType">
        <xs:sequence>
            <xs:element name="player" type="playerType" maxOccurs="unbounded" minOccurs="1"/>
            
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="playerType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="jerseyNumber" type="NullOrInteger" use="required"></xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:simpleType name="NullOrInteger">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d*|\s{0}" />
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== IstvnRozsa/xml_project/outputs/08xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<teams xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="schema08.xsd">
    <team id="9">
        <teamName>Ottawa Senators</teamName>
        <teamStats>
            <wins>29</wins>
            <losses>47</losses>
            <pts>64</pts>
        </teamStats>
        <players>
            <player jerseyNumber="54">Bobby Ryan</player>
            <player jerseyNumber="10">Tom Pyatt</player>
            <player jerseyNumber="42">Justin Falk</player>
            <player jerseyNumber="34">Paul Carey</player>
            <player jerseyNumber="15">Zack Smith</player>
            <player jerseyNumber="89">Mikkel Boedker</player>
            <player jerseyNumber="17">Cody Goloubef</player>
            <player jerseyNumber="90">Mark Borowiecki</player>
            <player jerseyNumber="95">Matt Duchene</player>
            <player jerseyNumber="56">Magnus Paajarvi</player>
            <player jerseyNumber="29">Stefan Elliott</player>
            <player jerseyNumber="6">Chris Wideman</player>
            <player jerseyNumber="90">Darren Archibald</player>
            <player jerseyNumber="24">Oscar Lindberg</player>
            <player jerseyNumber="61">Mark Stone</player>
            <player jerseyNumber="46">Erik Burgdoerfer</player>
            <player jerseyNumber="29">Brian Gibbons</player>
            <player jerseyNumber="19">Ryan Dzingel</player>
            <player jerseyNumber="71">Max McCormick</player>
            <player jerseyNumber="2">Dylan DeMelo</player>
            <player jerseyNumber="44">Jean-Gabriel Pageau</player>
            <player jerseyNumber="5">Cody Ceci</player>
            <player jerseyNumber="71">Chris Tierney</player>
            <player jerseyNumber="10">Anthony Duclair</player>
            <player jerseyNumber="20">Nicholas Paul</player>
            <player jerseyNumber="17">Ben Harpur</player>
            <player jerseyNumber="88">Andreas Englund</player>
            <player jerseyNumber="53">Jack Rodewald</player>
            <player jerseyNumber="6">Colin White</player>
            <player jerseyNumber="72">Thomas Chabot</player>
            <player jerseyNumber="78">Filip Chlapik</player>
            <player jerseyNumber="86">Christian Wolanin</player>
            <player jerseyNumber="83">Christian Jaros</player>
            <player jerseyNumber="22">Rudolfs Balcers</player>
            <player jerseyNumber="42">Maxime Lajoie</player>
            <player jerseyNumber="22">Logan Brown</player>
            <player jerseyNumber="85">Vitaly Abramov</player>
            <player jerseyNumber="10">Alex Formenton</player>
            <player jerseyNumber="26">Erik Brannstrom</player>
            <player jerseyNumber="19">Drake Batherson</player>
            <player jerseyNumber="74">Max Veronneau</player>
            <player jerseyNumber="7">Brady Tkachuk</player>
            <player jerseyNumber="41">Craig Anderson</player>
            <player jerseyNumber="56">Mike McKenna</player>
            <player jerseyNumber="">Anders Nilsson</player>
            <player jerseyNumber="1">Mike Condon</player>
            <player jerseyNumber="1">Marcus Hogberg</player>
            <player jerseyNumber="35">Joey Daccord</player>
        </players>
    </team>
    <team id="1">
        <teamName>New Jersey Devils</teamName>
        <teamStats>
            <wins>31</wins>
            <losses>41</losses>
            <pts>72</pts>
        </teamStats>
        <players>
            <player jerseyNumber="11">Brian Boyle</player>
            <player jerseyNumber="18">Drew Stafford</player>
            <player jerseyNumber="14">Travis Zajac</player>
            <player jerseyNumber="4">Andy Greene</player>
            <player jerseyNumber="2">Eric Gryba</player>
            <player jerseyNumber="21">Ben Lovejoy</player>
            <player jerseyNumber="34">Eric Tangradi</player>
            <player jerseyNumber="90">Marcus Johansson</player>
            <player jerseyNumber="21">Kyle Palmieri</player>
            <player jerseyNumber="45">Sami Vatanen</player>
            <player jerseyNumber="71">Taylor Hall</player>
            <player jerseyNumber="18">Kenny Agostino</player>
            <player jerseyNumber="56">Blake Pietila</player>
            <player jerseyNumber="20">Blake Coleman</player>
            <player jerseyNumber="87">Ryan Murphy</player>
            <player jerseyNumber="23">Stefan Noesen</player>
            <player jerseyNumber="79">Kurtis Gabriel</player>
            <player jerseyNumber="28">Damon Severson</player>
            <player jerseyNumber="58">Connor Carrick</player>
            <player jerseyNumber="33">Will Butcher</player>
            <player jerseyNumber="44">Miles Wood</player>
            <player jerseyNumber="36">Steven Santini</player>
            <player jerseyNumber="25">Mirco Mueller</player>
            <player jerseyNumber="">Jean-Sebastien Dea</player>
            <player jerseyNumber="47">John Quenneville</player>
            <player jerseyNumber="38">Josh Jacobs</player>
            <player jerseyNumber="18">Pavel Zacha</player>
            <player jerseyNumber="45">Colton White</player>
            <player jerseyNumber="62">Brett Seney</player>
            <player jerseyNumber="25">Nick Lappin</player>
            <player jerseyNumber="21">Kevin Rooney</player>
            <player jerseyNumber="28">Joey Anderson</player>
            <player jerseyNumber="51">Brandon Gignac</player>
            <player jerseyNumber="63">Jesper Bratt</player>
            <player jerseyNumber="14">Nathan Bastian</player>
            <player jerseyNumber="20">Michael McLeod</player>
            <player jerseyNumber="13">Nico Hischier</player>
            <player jerseyNumber="74">Egor Yakovlev</player>
            <player jerseyNumber="35">Cory Schneider</player>
            <player jerseyNumber="30">Keith Kinkaid</player>
            <player jerseyNumber="29">Mackenzie Blackwood</player>
        </players>
    </team>
    <team id="3">
        <teamName>New York Rangers</teamName>
        <teamStats>
            <wins>32</wins>
            <losses>36</losses>
            <pts>78</pts>
        </teamStats>
        <players>
            <player jerseyNumber="55">Cody McLeod</player>
            <player jerseyNumber="18">Marc Staal</player>
            <player jerseyNumber="54">Adam McQuaid</player>
            <player jerseyNumber="39">Matt Beleskey</player>
            <player jerseyNumber="22">Kevin Shattenkirk</player>
            <player jerseyNumber="2">Brendan Smith</player>
            <player jerseyNumber="20">Chris Kreider</player>
            <player jerseyNumber="36">Mats Zuccarello</player>
            <player jerseyNumber="15">Ryan Spooner</player>
            <player jerseyNumber="23">Connor Brickley</player>
            <player jerseyNumber="13">Kevin Hayes</player>
            <player jerseyNumber="71">Jesper Fast</player>
            <player jerseyNumber="3">Fredrik Claesson</player>
            <player jerseyNumber="28">Steven Fogarty</player>
            <player jerseyNumber="16">Ryan Strome</player>
            <player jerseyNumber="93">Mika Zibanejad</player>
            <player jerseyNumber="90">Vladislav Namestnikov</player>
            <player jerseyNumber="76">Brady Skjei</player>
            <player jerseyNumber="26">Jimmy Vesey</player>
            <player jerseyNumber="59">Boo Nieves</player>
            <player jerseyNumber="58">John Gilmour</player>
            <player jerseyNumber="89">Pavel Buchnevich</player>
            <player jerseyNumber="77">Tony DeAngelo</player>
            <player jerseyNumber="48">Brendan Lemieux</player>
            <player jerseyNumber="55">Ryan Lindgren</player>
            <player jerseyNumber="25">Libor Hajek</player>
            <player jerseyNumber="21">Brett Howden</player>
            <player jerseyNumber="42">Tim Gettinger</player>
            <player jerseyNumber="95">Vinni Lettieri</player>
            <player jerseyNumber="17">Lias Andersson</player>
            <player jerseyNumber="72">Filip Chytil</player>
            <player jerseyNumber="4">Neal Pionk</player>
            <player jerseyNumber="30">Henrik Lundqvist</player>
            <player jerseyNumber="40">Alexandar Georgiev</player>
        </players>
    </team>
    <team id="17">
        <teamName>Detroit Red Wings</teamName>
        <teamStats>
            <wins>32</wins>
            <losses>40</losses>
            <pts>74</pts>
        </teamStats>
        <players>
            <player jerseyNumber="55">Niklas Kronwall</player>
            <player jerseyNumber="83">Trevor Daley</player>
            <player jerseyNumber="81">Frans Nielsen</player>
            <player jerseyNumber="52">Jonathan Ericsson</player>
            <player jerseyNumber="26">Thomas Vanek</player>
            <player jerseyNumber="27">Mike Green</player>
            <player jerseyNumber="8">Justin Abdelkader</player>
            <player jerseyNumber="43">Darren Helm</player>
            <player jerseyNumber="14">Gustav Nyquist</player>
            <player jerseyNumber="28">Luke Witkowski</player>
            <player jerseyNumber="32">Brian Lashoff</player>
            <player jerseyNumber="22">Wade Megan</player>
            <player jerseyNumber="3">Nick Jensen</player>
            <player jerseyNumber="25">Dylan McIlrath</player>
            <player jerseyNumber="54">Matt Puempel</player>
            <player jerseyNumber="11">Luke Glendening</player>
            <player jerseyNumber="29">Martin Frk</player>
            <player jerseyNumber="89">Andreas Athanasiou</player>
            <player jerseyNumber="65">Danny DeKeyser</player>
            <player jerseyNumber="61">Jacob de la Rose</player>
            <player jerseyNumber="24">Madison Bowey</player>
            <player jerseyNumber="59">Tyler Bertuzzi</player>
            <player jerseyNumber="39">Anthony Mantha</player>
